# Macro to make sure we have a list of sources
macro (add_sources)
  file (RELATIVE_PATH _rel_path "${CMAKE_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
  foreach (_src ${ARGN})
    if (_rel_path)
      list (APPEND SRCS "${CMAKE_SOURCE_DIR}/${_rel_path}/${_src}")
    else()
      list (APPEND SRCS "${CMAKE_SOURCE_DIR}/${_src}")
    endif()
  endforeach()
  if (_rel_path)
    set (SRCS ${SRCS} PARENT_SCOPE)
  endif()
endmacro()
